version: "3.6"

services:
  money_tracker_db:
    image: postgres:11
    container_name: money_tracker_db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=money_tracker
    networks:
      - money_tracker-network
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data

  money_tracker_site:
    image: money_tracker:latest
    container_name: money_tracker_site
    environment:
      - C_FORCE_ROOT='true'
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Moscow
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=money_tracker
      - DB_HOST=money_tracker_db
    depends_on:
      - money_tracker_db
    networks:
      - money_tracker-network
    volumes:
      - ${SITE_PATH}:/app
    command: ./entrypoint.sh

networks:
  money_tracker-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_ADDRESS}